2021-07-12 18:03:18,490 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,493 ERROR    uncaught exception
2021-07-12 18:03:18,493 ERROR    
2021-07-12 18:03:18,538 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,539 ERROR    uncaught exception
2021-07-12 18:03:18,539 ERROR    
2021-07-12 18:03:18,585 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,585 ERROR    uncaught exception
2021-07-12 18:03:18,585 ERROR    
2021-07-12 18:03:18,631 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,632 ERROR    uncaught exception
2021-07-12 18:03:18,632 ERROR    
2021-07-12 18:03:18,677 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,678 ERROR    uncaught exception
2021-07-12 18:03:18,678 ERROR    
2021-07-12 18:03:18,726 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,727 ERROR    uncaught exception
2021-07-12 18:03:18,727 ERROR    
2021-07-12 18:03:18,772 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,773 ERROR    uncaught exception
2021-07-12 18:03:18,773 ERROR    
2021-07-12 18:03:18,819 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,819 ERROR    uncaught exception
2021-07-12 18:03:18,819 ERROR    
2021-07-12 18:03:18,865 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,867 ERROR    uncaught exception
2021-07-12 18:03:18,867 ERROR    
2021-07-12 18:03:18,911 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,913 ERROR    uncaught exception
2021-07-12 18:03:18,913 ERROR    
2021-07-12 18:03:18,960 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:18,960 ERROR    uncaught exception
2021-07-12 18:03:18,960 ERROR    
2021-07-12 18:03:19,006 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,006 ERROR    uncaught exception
2021-07-12 18:03:19,006 ERROR    
2021-07-12 18:03:19,076 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,079 ERROR    uncaught exception
2021-07-12 18:03:19,081 ERROR    
2021-07-12 18:03:19,099 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,101 ERROR    uncaught exception
2021-07-12 18:03:19,102 ERROR    
2021-07-12 18:03:19,148 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,150 ERROR    uncaught exception
2021-07-12 18:03:19,150 ERROR    
2021-07-12 18:03:19,194 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,196 ERROR    uncaught exception
2021-07-12 18:03:19,196 ERROR    
2021-07-12 18:03:19,240 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,240 ERROR    uncaught exception
2021-07-12 18:03:19,240 ERROR    
2021-07-12 18:03:19,286 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,289 ERROR    uncaught exception
2021-07-12 18:03:19,289 ERROR    
2021-07-12 18:03:19,336 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,338 ERROR    uncaught exception
2021-07-12 18:03:19,338 ERROR    
2021-07-12 18:03:19,381 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,382 ERROR    uncaught exception
2021-07-12 18:03:19,382 ERROR    
2021-07-12 18:03:19,427 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,428 ERROR    uncaught exception
2021-07-12 18:03:19,428 ERROR    
2021-07-12 18:03:19,473 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,476 ERROR    uncaught exception
2021-07-12 18:03:19,476 ERROR    
2021-07-12 18:03:19,519 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,520 ERROR    uncaught exception
2021-07-12 18:03:19,520 ERROR    
2021-07-12 18:03:19,566 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,568 ERROR    uncaught exception
2021-07-12 18:03:19,568 ERROR    
2021-07-12 18:03:19,615 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,615 ERROR    uncaught exception
2021-07-12 18:03:19,615 ERROR    
2021-07-12 18:03:19,661 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,661 ERROR    uncaught exception
2021-07-12 18:03:19,661 ERROR    
2021-07-12 18:03:19,709 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,710 ERROR    uncaught exception
2021-07-12 18:03:19,710 ERROR    
2021-07-12 18:03:19,756 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,757 ERROR    uncaught exception
2021-07-12 18:03:19,757 ERROR    
2021-07-12 18:03:19,802 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,805 ERROR    uncaught exception
2021-07-12 18:03:19,805 ERROR    
2021-07-12 18:03:19,851 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,855 ERROR    uncaught exception
2021-07-12 18:03:19,855 ERROR    
2021-07-12 18:03:19,898 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,901 ERROR    uncaught exception
2021-07-12 18:03:19,901 ERROR    
2021-07-12 18:03:19,944 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,946 ERROR    uncaught exception
2021-07-12 18:03:19,946 ERROR    
2021-07-12 18:03:19,990 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:19,992 ERROR    uncaught exception
2021-07-12 18:03:19,992 ERROR    
2021-07-12 18:03:20,036 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,038 ERROR    uncaught exception
2021-07-12 18:03:20,039 ERROR    
2021-07-12 18:03:20,084 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,085 ERROR    uncaught exception
2021-07-12 18:03:20,085 ERROR    
2021-07-12 18:03:20,135 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,138 ERROR    uncaught exception
2021-07-12 18:03:20,138 ERROR    
2021-07-12 18:03:20,177 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,181 ERROR    uncaught exception
2021-07-12 18:03:20,181 ERROR    
2021-07-12 18:03:20,226 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,233 ERROR    uncaught exception
2021-07-12 18:03:20,233 ERROR    
2021-07-12 18:03:20,275 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,276 ERROR    uncaught exception
2021-07-12 18:03:20,276 ERROR    
2021-07-12 18:03:20,321 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,323 ERROR    uncaught exception
2021-07-12 18:03:20,323 ERROR    
2021-07-12 18:03:20,365 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,368 ERROR    uncaught exception
2021-07-12 18:03:20,368 ERROR    
2021-07-12 18:03:20,411 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,413 ERROR    uncaught exception
2021-07-12 18:03:20,413 ERROR    
2021-07-12 18:03:20,460 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,463 ERROR    uncaught exception
2021-07-12 18:03:20,463 ERROR    
2021-07-12 18:03:20,506 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,509 ERROR    uncaught exception
2021-07-12 18:03:20,509 ERROR    
2021-07-12 18:03:20,552 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,555 ERROR    uncaught exception
2021-07-12 18:03:20,555 ERROR    
2021-07-12 18:03:20,599 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,601 ERROR    uncaught exception
2021-07-12 18:03:20,601 ERROR    
2021-07-12 18:03:20,648 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,650 ERROR    uncaught exception
2021-07-12 18:03:20,650 ERROR    
2021-07-12 18:03:20,694 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,697 ERROR    uncaught exception
2021-07-12 18:03:20,697 ERROR    
2021-07-12 18:03:20,740 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,742 ERROR    uncaught exception
2021-07-12 18:03:20,743 ERROR    
2021-07-12 18:03:20,788 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,789 ERROR    uncaught exception
2021-07-12 18:03:20,789 ERROR    
2021-07-12 18:03:20,832 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,834 ERROR    uncaught exception
2021-07-12 18:03:20,834 ERROR    
2021-07-12 18:03:20,884 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,888 ERROR    uncaught exception
2021-07-12 18:03:20,888 ERROR    
2021-07-12 18:03:20,927 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,933 ERROR    uncaught exception
2021-07-12 18:03:20,934 ERROR    
2021-07-12 18:03:20,977 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:20,980 ERROR    uncaught exception
2021-07-12 18:03:20,982 ERROR    
2021-07-12 18:03:21,023 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,026 ERROR    uncaught exception
2021-07-12 18:03:21,028 ERROR    
2021-07-12 18:03:21,068 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,069 ERROR    uncaught exception
2021-07-12 18:03:21,069 ERROR    
2021-07-12 18:03:21,115 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,118 ERROR    uncaught exception
2021-07-12 18:03:21,118 ERROR    
2021-07-12 18:03:21,163 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,165 ERROR    uncaught exception
2021-07-12 18:03:21,165 ERROR    
2021-07-12 18:03:21,210 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,213 ERROR    uncaught exception
2021-07-12 18:03:21,213 ERROR    
2021-07-12 18:03:21,259 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,263 ERROR    uncaught exception
2021-07-12 18:03:21,263 ERROR    
2021-07-12 18:03:21,303 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,308 ERROR    uncaught exception
2021-07-12 18:03:21,308 ERROR    
2021-07-12 18:03:21,354 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,358 ERROR    uncaught exception
2021-07-12 18:03:21,358 ERROR    
2021-07-12 18:03:21,398 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,401 ERROR    uncaught exception
2021-07-12 18:03:21,401 ERROR    
2021-07-12 18:03:21,443 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,446 ERROR    uncaught exception
2021-07-12 18:03:21,446 ERROR    
2021-07-12 18:03:21,490 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,493 ERROR    uncaught exception
2021-07-12 18:03:21,493 ERROR    
2021-07-12 18:03:21,539 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,542 ERROR    uncaught exception
2021-07-12 18:03:21,542 ERROR    
2021-07-12 18:03:21,584 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,586 ERROR    uncaught exception
2021-07-12 18:03:21,588 ERROR    
2021-07-12 18:03:21,634 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,638 ERROR    uncaught exception
2021-07-12 18:03:21,638 ERROR    
2021-07-12 18:03:21,680 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,681 ERROR    uncaught exception
2021-07-12 18:03:21,681 ERROR    
2021-07-12 18:03:21,726 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,729 ERROR    uncaught exception
2021-07-12 18:03:21,729 ERROR    
2021-07-12 18:03:21,773 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,775 ERROR    uncaught exception
2021-07-12 18:03:21,776 ERROR    
2021-07-12 18:03:21,818 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,819 ERROR    uncaught exception
2021-07-12 18:03:21,819 ERROR    
2021-07-12 18:03:21,865 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,868 ERROR    uncaught exception
2021-07-12 18:03:21,868 ERROR    
2021-07-12 18:03:21,914 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,915 ERROR    uncaught exception
2021-07-12 18:03:21,915 ERROR    
2021-07-12 18:03:21,963 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:21,964 ERROR    uncaught exception
2021-07-12 18:03:21,966 ERROR    
2021-07-12 18:03:22,013 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,017 ERROR    uncaught exception
2021-07-12 18:03:22,019 ERROR    
2021-07-12 18:03:22,052 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,055 ERROR    uncaught exception
2021-07-12 18:03:22,055 ERROR    
2021-07-12 18:03:22,098 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,101 ERROR    uncaught exception
2021-07-12 18:03:22,101 ERROR    
2021-07-12 18:03:22,148 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,151 ERROR    uncaught exception
2021-07-12 18:03:22,151 ERROR    
2021-07-12 18:03:22,194 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,198 ERROR    uncaught exception
2021-07-12 18:03:22,198 ERROR    
2021-07-12 18:03:22,240 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,244 ERROR    uncaught exception
2021-07-12 18:03:22,246 ERROR    
2021-07-12 18:03:22,292 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,296 ERROR    uncaught exception
2021-07-12 18:03:22,298 ERROR    
2021-07-12 18:03:22,341 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,346 ERROR    uncaught exception
2021-07-12 18:03:22,348 ERROR    
2021-07-12 18:03:22,382 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,385 ERROR    uncaught exception
2021-07-12 18:03:22,385 ERROR    
2021-07-12 18:03:22,427 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,428 ERROR    uncaught exception
2021-07-12 18:03:22,428 ERROR    
2021-07-12 18:03:22,474 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,476 ERROR    uncaught exception
2021-07-12 18:03:22,476 ERROR    
2021-07-12 18:03:22,522 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,523 ERROR    uncaught exception
2021-07-12 18:03:22,523 ERROR    
2021-07-12 18:03:22,568 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,569 ERROR    uncaught exception
2021-07-12 18:03:22,569 ERROR    
2021-07-12 18:03:22,614 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,615 ERROR    uncaught exception
2021-07-12 18:03:22,615 ERROR    
2021-07-12 18:03:22,663 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,664 ERROR    uncaught exception
2021-07-12 18:03:22,664 ERROR    
2021-07-12 18:03:22,710 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,710 ERROR    uncaught exception
2021-07-12 18:03:22,710 ERROR    
2021-07-12 18:03:22,755 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 314, in updatePlots
    self.updateValueLabels()
  File "E:\Dokumente\Studium\Bachelorarbeit\02_Programm\microRay-devel\gui\plotWidget.py", line 361, in updateValueLabels
    xData, yData = firstCurve.getData()
AttributeError: 'NoneType' object has no attribute 'getData'

2021-07-12 18:03:22,756 ERROR    uncaught exception
2021-07-12 18:03:22,756 ERROR    
